#!/usr/bin/env bash
# Summary: Show the current kubectl version and its origin
#
# Shows the currently selected kubectl version and how it was selected.
# To obtain only the version string, use `kcenv version-name'.

set -e
[ -n "$KCENV_DEBUG" ] && set -x

echo "$(kcenv-version-name) (set by $(kcenv-version-origin))"
