#!/usr/bin/env bash
#
# Summary: Run kubectl with the selected version
#
# Usage: kcenv exec [arg1 arg2...]
#
# Runs kubectl by first preparing PATH so that the selected
# version's `bin' directory is at the front.
#
# For example, if the currently selected kubectl version is 1.11.3:
#   kcenv exec version
#
# is equivalent to:
#   PATH="$KCENV_ROOT/versions/1.11.3:$PATH" kubectl version

set -e
[ -n "${KCENV_DEBUG}" ] && set -x

export KUBECTL_BIN_PATH=$(kcenv-bin-path)
if [ -z "${KUBECTL_BIN_PATH}" ]; then
  exit 1
fi

export KUBECTL="${KUBECTL_BIN_PATH}/kubectl"
if [ ! -x "${KUBECTL}" ]; then
  exit 1
fi

exec "${KUBECTL}" "${@}"
