#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific kubectl version
#
# Usage: kcenv local <version>
#        kcenv local --unset
#
# Sets the local application-specific kubectl version by writing the
# version name to a file named `.kubectl-version'.
#
# When you run a kubectl command, kcenv will look for a `.kubectl-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, kcenv will use the global kubectl version
# specified with `kcenv global'. A version specified with the
# `KCENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a kubectl version known to kcenv.
# The special version string `system' will use your default system kubectl.
# Run `kcenv versions' for a list of available kubectl versions.

set -e
[ -n "$KCENV_DEBUG" ] && set -x

# Provide kcenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec kcenv-versions --bare
fi

KCENV_VERSION="$1"

if [ "$KCENV_VERSION" = "--unset" ]; then
  rm -f .kubectl-version
elif [ -n "$KCENV_VERSION" ]; then
  kcenv-version-file-write .kubectl-version "$KCENV_VERSION"
else
  if version_file="$(kcenv-version-file "$PWD")"; then
    kcenv-version-file-read "$version_file"
  else
    echo "kcenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
